export const JAMAICAN_SCHOOLS = [
  'Anchovy High','Ardenne High','Belair High','Belmont Academy','Bishop Gibson High',
  'Black River High','Brimmervale High',"Brown's Town High",'Buff Bay High',
  'Calabar High','Cambridge High','Campion College','Camperdown High','Charlemont High',
  'Clarendon College','Cornwall College','deCarteret College','Denbigh High',
  'Dinthill Technical High','Edwin Allen High','Excelsior High','Ferncourt High',
  'Frome Technical','Glenmuir High','Graduate','Green Island High','Guys Hill High',
  'Hampton School','Happy Grove High','Harrison Memorial High','Herbert Morrison Technical',
  'Holmwood Technical','Holy Childhood High','Hopewell High','Immaculate Conception High',
  'Iona High','Irwin High','Jamaica College','Jonathan Grant High','Knox College',
  'Lacovia High','Maggotty High','Maldon High','Manchester High',"Manning's School",
  'Marcus Garvey Technical','Marymount High','Meadowbrook High','Montego Bay High',
  'Morant Bay High','Mount Alvernia High','Munro College','Muschett High','Newell High',
  'Norman Manley High','Ocho Rios High','Old Harbour High','Paul Bogle High',
  'Port Antonio High','Rhodes Hall High','Robert Lightbourne High',"Rusea's High",
  'Seaforth High','Spanish Town High','St. Andrew High for Girls','St. Andrew Technical High',
  'St. Catherine High','St. Elizabeth Technical',"St. George's College","St. Hilda's High",
  'St. Jago High','St. James High','St. Mary High','St. Thomas Technical','Tacky High',
  'Titchfield High','Upper Six','Vere Technical','Westwood High','William Knibb Memorial',
  "Wolmer's Boys' School","Wolmer's Girls' School",'Yallahs High','York Castle High','Other',
];
